# Labels for labeling issues and pull requests using GitHub prow action.
kind:
  - 'bug'
  - 'feature'
  - 'documentation'
  - 'cleanup'
  - 'support'

priority:
  - 'important-soon'
  - 'important-longterm'
