DROP TABLE IF EXISTS access_tokens;
DROP TABLE IF EXISTS datasets;
DROP TABLE IF EXISTS models;
DROP TABLE IF EXISTS members_roles_projects;
DROP TABLE IF EXISTS projects;
DROP TABLE IF EXISTS roles;
DROP TABLE IF EXISTS users;

