// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.5
// source: v1alpha1/model.proto

package v1alpha1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Models_ListModels_FullMethodName          = "/matrixhub.v1alpha1.Models/ListModels"
	Models_GetModel_FullMethodName            = "/matrixhub.v1alpha1.Models/GetModel"
	Models_CreateModel_FullMethodName         = "/matrixhub.v1alpha1.Models/CreateModel"
	Models_DeleteModel_FullMethodName         = "/matrixhub.v1alpha1.Models/DeleteModel"
	Models_ListModelBranches_FullMethodName   = "/matrixhub.v1alpha1.Models/ListModelBranches"
	Models_ListModelTags_FullMethodName       = "/matrixhub.v1alpha1.Models/ListModelTags"
	Models_GetModelLastCommit_FullMethodName  = "/matrixhub.v1alpha1.Models/GetModelLastCommit"
	Models_GetModelCommit_FullMethodName      = "/matrixhub.v1alpha1.Models/GetModelCommit"
	Models_GetModelTreeCommits_FullMethodName = "/matrixhub.v1alpha1.Models/GetModelTreeCommits"
	Models_GetModelTree_FullMethodName        = "/matrixhub.v1alpha1.Models/GetModelTree"
	Models_GetModelBlob_FullMethodName        = "/matrixhub.v1alpha1.Models/GetModelBlob"
)

// ModelsClient is the client API for Models service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ModelsClient interface {
	ListModels(ctx context.Context, in *ListModelsRequest, opts ...grpc.CallOption) (*ListModelsResponse, error)
	GetModel(ctx context.Context, in *GetModelRequest, opts ...grpc.CallOption) (*GetModelResponse, error)
	CreateModel(ctx context.Context, in *CreateModelRequest, opts ...grpc.CallOption) (*CreateModelResponse, error)
	DeleteModel(ctx context.Context, in *DeleteModelRequest, opts ...grpc.CallOption) (*DeleteModelResponse, error)
	ListModelBranches(ctx context.Context, in *ListModelBranchesRequest, opts ...grpc.CallOption) (*ListModelBranchesResponse, error)
	ListModelTags(ctx context.Context, in *ListModelTagsRequest, opts ...grpc.CallOption) (*ListModelTagsResponse, error)
	GetModelLastCommit(ctx context.Context, in *GetModelLastCommitRequest, opts ...grpc.CallOption) (*GetModelLastCommitResponse, error)
	GetModelCommit(ctx context.Context, in *GetModelCommitRequest, opts ...grpc.CallOption) (*GetModelCommitResponse, error)
	GetModelTreeCommits(ctx context.Context, in *GetModelTreeCommitsRequest, opts ...grpc.CallOption) (*GetModelTreeCommitsResponse, error)
	GetModelTree(ctx context.Context, in *GetModelTreeRequest, opts ...grpc.CallOption) (*GetModelTreeResponse, error)
	GetModelBlob(ctx context.Context, in *GetModelBlobRequest, opts ...grpc.CallOption) (*GetModelBlobResponse, error)
}

type modelsClient struct {
	cc grpc.ClientConnInterface
}

func NewModelsClient(cc grpc.ClientConnInterface) ModelsClient {
	return &modelsClient{cc}
}

func (c *modelsClient) ListModels(ctx context.Context, in *ListModelsRequest, opts ...grpc.CallOption) (*ListModelsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListModelsResponse)
	err := c.cc.Invoke(ctx, Models_ListModels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelsClient) GetModel(ctx context.Context, in *GetModelRequest, opts ...grpc.CallOption) (*GetModelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetModelResponse)
	err := c.cc.Invoke(ctx, Models_GetModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelsClient) CreateModel(ctx context.Context, in *CreateModelRequest, opts ...grpc.CallOption) (*CreateModelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateModelResponse)
	err := c.cc.Invoke(ctx, Models_CreateModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelsClient) DeleteModel(ctx context.Context, in *DeleteModelRequest, opts ...grpc.CallOption) (*DeleteModelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteModelResponse)
	err := c.cc.Invoke(ctx, Models_DeleteModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelsClient) ListModelBranches(ctx context.Context, in *ListModelBranchesRequest, opts ...grpc.CallOption) (*ListModelBranchesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListModelBranchesResponse)
	err := c.cc.Invoke(ctx, Models_ListModelBranches_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelsClient) ListModelTags(ctx context.Context, in *ListModelTagsRequest, opts ...grpc.CallOption) (*ListModelTagsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListModelTagsResponse)
	err := c.cc.Invoke(ctx, Models_ListModelTags_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelsClient) GetModelLastCommit(ctx context.Context, in *GetModelLastCommitRequest, opts ...grpc.CallOption) (*GetModelLastCommitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetModelLastCommitResponse)
	err := c.cc.Invoke(ctx, Models_GetModelLastCommit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelsClient) GetModelCommit(ctx context.Context, in *GetModelCommitRequest, opts ...grpc.CallOption) (*GetModelCommitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetModelCommitResponse)
	err := c.cc.Invoke(ctx, Models_GetModelCommit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelsClient) GetModelTreeCommits(ctx context.Context, in *GetModelTreeCommitsRequest, opts ...grpc.CallOption) (*GetModelTreeCommitsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetModelTreeCommitsResponse)
	err := c.cc.Invoke(ctx, Models_GetModelTreeCommits_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelsClient) GetModelTree(ctx context.Context, in *GetModelTreeRequest, opts ...grpc.CallOption) (*GetModelTreeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetModelTreeResponse)
	err := c.cc.Invoke(ctx, Models_GetModelTree_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelsClient) GetModelBlob(ctx context.Context, in *GetModelBlobRequest, opts ...grpc.CallOption) (*GetModelBlobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetModelBlobResponse)
	err := c.cc.Invoke(ctx, Models_GetModelBlob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ModelsServer is the server API for Models service.
// All implementations should embed UnimplementedModelsServer
// for forward compatibility.
type ModelsServer interface {
	ListModels(context.Context, *ListModelsRequest) (*ListModelsResponse, error)
	GetModel(context.Context, *GetModelRequest) (*GetModelResponse, error)
	CreateModel(context.Context, *CreateModelRequest) (*CreateModelResponse, error)
	DeleteModel(context.Context, *DeleteModelRequest) (*DeleteModelResponse, error)
	ListModelBranches(context.Context, *ListModelBranchesRequest) (*ListModelBranchesResponse, error)
	ListModelTags(context.Context, *ListModelTagsRequest) (*ListModelTagsResponse, error)
	GetModelLastCommit(context.Context, *GetModelLastCommitRequest) (*GetModelLastCommitResponse, error)
	GetModelCommit(context.Context, *GetModelCommitRequest) (*GetModelCommitResponse, error)
	GetModelTreeCommits(context.Context, *GetModelTreeCommitsRequest) (*GetModelTreeCommitsResponse, error)
	GetModelTree(context.Context, *GetModelTreeRequest) (*GetModelTreeResponse, error)
	GetModelBlob(context.Context, *GetModelBlobRequest) (*GetModelBlobResponse, error)
}

// UnimplementedModelsServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedModelsServer struct{}

func (UnimplementedModelsServer) ListModels(context.Context, *ListModelsRequest) (*ListModelsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListModels not implemented")
}
func (UnimplementedModelsServer) GetModel(context.Context, *GetModelRequest) (*GetModelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetModel not implemented")
}
func (UnimplementedModelsServer) CreateModel(context.Context, *CreateModelRequest) (*CreateModelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateModel not implemented")
}
func (UnimplementedModelsServer) DeleteModel(context.Context, *DeleteModelRequest) (*DeleteModelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteModel not implemented")
}
func (UnimplementedModelsServer) ListModelBranches(context.Context, *ListModelBranchesRequest) (*ListModelBranchesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListModelBranches not implemented")
}
func (UnimplementedModelsServer) ListModelTags(context.Context, *ListModelTagsRequest) (*ListModelTagsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListModelTags not implemented")
}
func (UnimplementedModelsServer) GetModelLastCommit(context.Context, *GetModelLastCommitRequest) (*GetModelLastCommitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetModelLastCommit not implemented")
}
func (UnimplementedModelsServer) GetModelCommit(context.Context, *GetModelCommitRequest) (*GetModelCommitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetModelCommit not implemented")
}
func (UnimplementedModelsServer) GetModelTreeCommits(context.Context, *GetModelTreeCommitsRequest) (*GetModelTreeCommitsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetModelTreeCommits not implemented")
}
func (UnimplementedModelsServer) GetModelTree(context.Context, *GetModelTreeRequest) (*GetModelTreeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetModelTree not implemented")
}
func (UnimplementedModelsServer) GetModelBlob(context.Context, *GetModelBlobRequest) (*GetModelBlobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetModelBlob not implemented")
}
func (UnimplementedModelsServer) testEmbeddedByValue() {}

// UnsafeModelsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ModelsServer will
// result in compilation errors.
type UnsafeModelsServer interface {
	mustEmbedUnimplementedModelsServer()
}

func RegisterModelsServer(s grpc.ServiceRegistrar, srv ModelsServer) {
	// If the following call panics, it indicates UnimplementedModelsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Models_ServiceDesc, srv)
}

func _Models_ListModels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListModelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelsServer).ListModels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Models_ListModels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelsServer).ListModels(ctx, req.(*ListModelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Models_GetModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelsServer).GetModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Models_GetModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelsServer).GetModel(ctx, req.(*GetModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Models_CreateModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelsServer).CreateModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Models_CreateModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelsServer).CreateModel(ctx, req.(*CreateModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Models_DeleteModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelsServer).DeleteModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Models_DeleteModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelsServer).DeleteModel(ctx, req.(*DeleteModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Models_ListModelBranches_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListModelBranchesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelsServer).ListModelBranches(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Models_ListModelBranches_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelsServer).ListModelBranches(ctx, req.(*ListModelBranchesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Models_ListModelTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListModelTagsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelsServer).ListModelTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Models_ListModelTags_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelsServer).ListModelTags(ctx, req.(*ListModelTagsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Models_GetModelLastCommit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetModelLastCommitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelsServer).GetModelLastCommit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Models_GetModelLastCommit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelsServer).GetModelLastCommit(ctx, req.(*GetModelLastCommitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Models_GetModelCommit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetModelCommitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelsServer).GetModelCommit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Models_GetModelCommit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelsServer).GetModelCommit(ctx, req.(*GetModelCommitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Models_GetModelTreeCommits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetModelTreeCommitsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelsServer).GetModelTreeCommits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Models_GetModelTreeCommits_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelsServer).GetModelTreeCommits(ctx, req.(*GetModelTreeCommitsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Models_GetModelTree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetModelTreeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelsServer).GetModelTree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Models_GetModelTree_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelsServer).GetModelTree(ctx, req.(*GetModelTreeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Models_GetModelBlob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetModelBlobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelsServer).GetModelBlob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Models_GetModelBlob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelsServer).GetModelBlob(ctx, req.(*GetModelBlobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Models_ServiceDesc is the grpc.ServiceDesc for Models service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Models_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "matrixhub.v1alpha1.Models",
	HandlerType: (*ModelsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListModels",
			Handler:    _Models_ListModels_Handler,
		},
		{
			MethodName: "GetModel",
			Handler:    _Models_GetModel_Handler,
		},
		{
			MethodName: "CreateModel",
			Handler:    _Models_CreateModel_Handler,
		},
		{
			MethodName: "DeleteModel",
			Handler:    _Models_DeleteModel_Handler,
		},
		{
			MethodName: "ListModelBranches",
			Handler:    _Models_ListModelBranches_Handler,
		},
		{
			MethodName: "ListModelTags",
			Handler:    _Models_ListModelTags_Handler,
		},
		{
			MethodName: "GetModelLastCommit",
			Handler:    _Models_GetModelLastCommit_Handler,
		},
		{
			MethodName: "GetModelCommit",
			Handler:    _Models_GetModelCommit_Handler,
		},
		{
			MethodName: "GetModelTreeCommits",
			Handler:    _Models_GetModelTreeCommits_Handler,
		},
		{
			MethodName: "GetModelTree",
			Handler:    _Models_GetModelTree_Handler,
		},
		{
			MethodName: "GetModelBlob",
			Handler:    _Models_GetModelBlob_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1alpha1/model.proto",
}
