// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: v1alpha1/model.proto

package v1alpha1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on ListModelsRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ListModelsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListModelsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListModelsRequestMultiError, or nil if none found.
func (m *ListModelsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListModelsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Label

	// no validation rules for Search

	// no validation rules for Sort

	// no validation rules for Page

	// no validation rules for PageSize

	if len(errors) > 0 {
		return ListModelsRequestMultiError(errors)
	}

	return nil
}

// ListModelsRequestMultiError is an error wrapping multiple validation errors
// returned by ListModelsRequest.ValidateAll() if the designated constraints
// aren't met.
type ListModelsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListModelsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListModelsRequestMultiError) AllErrors() []error { return m }

// ListModelsRequestValidationError is the validation error returned by
// ListModelsRequest.Validate if the designated constraints aren't met.
type ListModelsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListModelsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListModelsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListModelsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListModelsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListModelsRequestValidationError) ErrorName() string {
	return "ListModelsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListModelsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListModelsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListModelsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListModelsRequestValidationError{}

// Validate checks the field values on ListModelsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListModelsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListModelsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListModelsResponseMultiError, or nil if none found.
func (m *ListModelsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListModelsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetItem() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListModelsResponseValidationError{
						field:  fmt.Sprintf("Item[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListModelsResponseValidationError{
						field:  fmt.Sprintf("Item[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListModelsResponseValidationError{
					field:  fmt.Sprintf("Item[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if all {
		switch v := interface{}(m.GetPagination()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ListModelsResponseValidationError{
					field:  "Pagination",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ListModelsResponseValidationError{
					field:  "Pagination",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetPagination()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ListModelsResponseValidationError{
				field:  "Pagination",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ListModelsResponseMultiError(errors)
	}

	return nil
}

// ListModelsResponseMultiError is an error wrapping multiple validation errors
// returned by ListModelsResponse.ValidateAll() if the designated constraints
// aren't met.
type ListModelsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListModelsResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListModelsResponseMultiError) AllErrors() []error { return m }

// ListModelsResponseValidationError is the validation error returned by
// ListModelsResponse.Validate if the designated constraints aren't met.
type ListModelsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListModelsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListModelsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListModelsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListModelsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListModelsResponseValidationError) ErrorName() string {
	return "ListModelsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListModelsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListModelsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListModelsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListModelsResponseValidationError{}

// Validate checks the field values on GetModelRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetModelRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetModelRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetModelRequestMultiError, or nil if none found.
func (m *GetModelRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetModelRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetProject()) < 1 {
		err := GetModelRequestValidationError{
			field:  "Project",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetModelName()) < 1 {
		err := GetModelRequestValidationError{
			field:  "ModelName",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return GetModelRequestMultiError(errors)
	}

	return nil
}

// GetModelRequestMultiError is an error wrapping multiple validation errors
// returned by GetModelRequest.ValidateAll() if the designated constraints
// aren't met.
type GetModelRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetModelRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetModelRequestMultiError) AllErrors() []error { return m }

// GetModelRequestValidationError is the validation error returned by
// GetModelRequest.Validate if the designated constraints aren't met.
type GetModelRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetModelRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetModelRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetModelRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetModelRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetModelRequestValidationError) ErrorName() string { return "GetModelRequestValidationError" }

// Error satisfies the builtin error interface
func (e GetModelRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetModelRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetModelRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetModelRequestValidationError{}

// Validate checks the field values on GetModelResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetModelResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetModelResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetModelResponseMultiError, or nil if none found.
func (m *GetModelResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetModelResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetModel()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetModelResponseValidationError{
					field:  "Model",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetModelResponseValidationError{
					field:  "Model",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetModel()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetModelResponseValidationError{
				field:  "Model",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetModelResponseMultiError(errors)
	}

	return nil
}

// GetModelResponseMultiError is an error wrapping multiple validation errors
// returned by GetModelResponse.ValidateAll() if the designated constraints
// aren't met.
type GetModelResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetModelResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetModelResponseMultiError) AllErrors() []error { return m }

// GetModelResponseValidationError is the validation error returned by
// GetModelResponse.Validate if the designated constraints aren't met.
type GetModelResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetModelResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetModelResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetModelResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetModelResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetModelResponseValidationError) ErrorName() string { return "GetModelResponseValidationError" }

// Error satisfies the builtin error interface
func (e GetModelResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetModelResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetModelResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetModelResponseValidationError{}

// Validate checks the field values on CreateModelRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateModelRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateModelRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateModelRequestMultiError, or nil if none found.
func (m *CreateModelRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateModelRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetProject()) < 1 {
		err := CreateModelRequestValidationError{
			field:  "Project",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetModelName()) < 1 {
		err := CreateModelRequestValidationError{
			field:  "ModelName",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return CreateModelRequestMultiError(errors)
	}

	return nil
}

// CreateModelRequestMultiError is an error wrapping multiple validation errors
// returned by CreateModelRequest.ValidateAll() if the designated constraints
// aren't met.
type CreateModelRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateModelRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateModelRequestMultiError) AllErrors() []error { return m }

// CreateModelRequestValidationError is the validation error returned by
// CreateModelRequest.Validate if the designated constraints aren't met.
type CreateModelRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateModelRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateModelRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateModelRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateModelRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateModelRequestValidationError) ErrorName() string {
	return "CreateModelRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateModelRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateModelRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateModelRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateModelRequestValidationError{}

// Validate checks the field values on CreateModelResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateModelResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateModelResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateModelResponseMultiError, or nil if none found.
func (m *CreateModelResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateModelResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return CreateModelResponseMultiError(errors)
	}

	return nil
}

// CreateModelResponseMultiError is an error wrapping multiple validation
// errors returned by CreateModelResponse.ValidateAll() if the designated
// constraints aren't met.
type CreateModelResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateModelResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateModelResponseMultiError) AllErrors() []error { return m }

// CreateModelResponseValidationError is the validation error returned by
// CreateModelResponse.Validate if the designated constraints aren't met.
type CreateModelResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateModelResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateModelResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateModelResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateModelResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateModelResponseValidationError) ErrorName() string {
	return "CreateModelResponseValidationError"
}

// Error satisfies the builtin error interface
func (e CreateModelResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateModelResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateModelResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateModelResponseValidationError{}

// Validate checks the field values on DeleteModelRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteModelRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteModelRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteModelRequestMultiError, or nil if none found.
func (m *DeleteModelRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteModelRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetProject()) < 1 {
		err := DeleteModelRequestValidationError{
			field:  "Project",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetModelName()) < 1 {
		err := DeleteModelRequestValidationError{
			field:  "ModelName",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return DeleteModelRequestMultiError(errors)
	}

	return nil
}

// DeleteModelRequestMultiError is an error wrapping multiple validation errors
// returned by DeleteModelRequest.ValidateAll() if the designated constraints
// aren't met.
type DeleteModelRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteModelRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteModelRequestMultiError) AllErrors() []error { return m }

// DeleteModelRequestValidationError is the validation error returned by
// DeleteModelRequest.Validate if the designated constraints aren't met.
type DeleteModelRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteModelRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteModelRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteModelRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteModelRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteModelRequestValidationError) ErrorName() string {
	return "DeleteModelRequestValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteModelRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteModelRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteModelRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteModelRequestValidationError{}

// Validate checks the field values on DeleteModelResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteModelResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteModelResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteModelResponseMultiError, or nil if none found.
func (m *DeleteModelResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteModelResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return DeleteModelResponseMultiError(errors)
	}

	return nil
}

// DeleteModelResponseMultiError is an error wrapping multiple validation
// errors returned by DeleteModelResponse.ValidateAll() if the designated
// constraints aren't met.
type DeleteModelResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteModelResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteModelResponseMultiError) AllErrors() []error { return m }

// DeleteModelResponseValidationError is the validation error returned by
// DeleteModelResponse.Validate if the designated constraints aren't met.
type DeleteModelResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteModelResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteModelResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteModelResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteModelResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteModelResponseValidationError) ErrorName() string {
	return "DeleteModelResponseValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteModelResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteModelResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteModelResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteModelResponseValidationError{}

// Validate checks the field values on ListModelBranchesRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListModelBranchesRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListModelBranchesRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListModelBranchesRequestMultiError, or nil if none found.
func (m *ListModelBranchesRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListModelBranchesRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetProject()) < 1 {
		err := ListModelBranchesRequestValidationError{
			field:  "Project",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetModelName()) < 1 {
		err := ListModelBranchesRequestValidationError{
			field:  "ModelName",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Page

	// no validation rules for PageSize

	if len(errors) > 0 {
		return ListModelBranchesRequestMultiError(errors)
	}

	return nil
}

// ListModelBranchesRequestMultiError is an error wrapping multiple validation
// errors returned by ListModelBranchesRequest.ValidateAll() if the designated
// constraints aren't met.
type ListModelBranchesRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListModelBranchesRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListModelBranchesRequestMultiError) AllErrors() []error { return m }

// ListModelBranchesRequestValidationError is the validation error returned by
// ListModelBranchesRequest.Validate if the designated constraints aren't met.
type ListModelBranchesRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListModelBranchesRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListModelBranchesRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListModelBranchesRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListModelBranchesRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListModelBranchesRequestValidationError) ErrorName() string {
	return "ListModelBranchesRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListModelBranchesRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListModelBranchesRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListModelBranchesRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListModelBranchesRequestValidationError{}

// Validate checks the field values on ListModelBranchesResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListModelBranchesResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListModelBranchesResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListModelBranchesResponseMultiError, or nil if none found.
func (m *ListModelBranchesResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListModelBranchesResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetItems() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListModelBranchesResponseValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListModelBranchesResponseValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListModelBranchesResponseValidationError{
					field:  fmt.Sprintf("Items[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ListModelBranchesResponseMultiError(errors)
	}

	return nil
}

// ListModelBranchesResponseMultiError is an error wrapping multiple validation
// errors returned by ListModelBranchesResponse.ValidateAll() if the
// designated constraints aren't met.
type ListModelBranchesResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListModelBranchesResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListModelBranchesResponseMultiError) AllErrors() []error { return m }

// ListModelBranchesResponseValidationError is the validation error returned by
// ListModelBranchesResponse.Validate if the designated constraints aren't met.
type ListModelBranchesResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListModelBranchesResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListModelBranchesResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListModelBranchesResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListModelBranchesResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListModelBranchesResponseValidationError) ErrorName() string {
	return "ListModelBranchesResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListModelBranchesResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListModelBranchesResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListModelBranchesResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListModelBranchesResponseValidationError{}

// Validate checks the field values on ListModelTagsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListModelTagsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListModelTagsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListModelTagsRequestMultiError, or nil if none found.
func (m *ListModelTagsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListModelTagsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetProject()) < 1 {
		err := ListModelTagsRequestValidationError{
			field:  "Project",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetModelName()) < 1 {
		err := ListModelTagsRequestValidationError{
			field:  "ModelName",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Page

	// no validation rules for PageSize

	if len(errors) > 0 {
		return ListModelTagsRequestMultiError(errors)
	}

	return nil
}

// ListModelTagsRequestMultiError is an error wrapping multiple validation
// errors returned by ListModelTagsRequest.ValidateAll() if the designated
// constraints aren't met.
type ListModelTagsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListModelTagsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListModelTagsRequestMultiError) AllErrors() []error { return m }

// ListModelTagsRequestValidationError is the validation error returned by
// ListModelTagsRequest.Validate if the designated constraints aren't met.
type ListModelTagsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListModelTagsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListModelTagsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListModelTagsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListModelTagsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListModelTagsRequestValidationError) ErrorName() string {
	return "ListModelTagsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListModelTagsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListModelTagsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListModelTagsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListModelTagsRequestValidationError{}

// Validate checks the field values on ListModelTagsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListModelTagsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListModelTagsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListModelTagsResponseMultiError, or nil if none found.
func (m *ListModelTagsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListModelTagsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetItems() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListModelTagsResponseValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListModelTagsResponseValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListModelTagsResponseValidationError{
					field:  fmt.Sprintf("Items[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ListModelTagsResponseMultiError(errors)
	}

	return nil
}

// ListModelTagsResponseMultiError is an error wrapping multiple validation
// errors returned by ListModelTagsResponse.ValidateAll() if the designated
// constraints aren't met.
type ListModelTagsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListModelTagsResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListModelTagsResponseMultiError) AllErrors() []error { return m }

// ListModelTagsResponseValidationError is the validation error returned by
// ListModelTagsResponse.Validate if the designated constraints aren't met.
type ListModelTagsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListModelTagsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListModelTagsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListModelTagsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListModelTagsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListModelTagsResponseValidationError) ErrorName() string {
	return "ListModelTagsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListModelTagsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListModelTagsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListModelTagsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListModelTagsResponseValidationError{}

// Validate checks the field values on GetModelLastCommitRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetModelLastCommitRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetModelLastCommitRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetModelLastCommitRequestMultiError, or nil if none found.
func (m *GetModelLastCommitRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetModelLastCommitRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetProject()) < 1 {
		err := GetModelLastCommitRequestValidationError{
			field:  "Project",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetModelName()) < 1 {
		err := GetModelLastCommitRequestValidationError{
			field:  "ModelName",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return GetModelLastCommitRequestMultiError(errors)
	}

	return nil
}

// GetModelLastCommitRequestMultiError is an error wrapping multiple validation
// errors returned by GetModelLastCommitRequest.ValidateAll() if the
// designated constraints aren't met.
type GetModelLastCommitRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetModelLastCommitRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetModelLastCommitRequestMultiError) AllErrors() []error { return m }

// GetModelLastCommitRequestValidationError is the validation error returned by
// GetModelLastCommitRequest.Validate if the designated constraints aren't met.
type GetModelLastCommitRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetModelLastCommitRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetModelLastCommitRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetModelLastCommitRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetModelLastCommitRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetModelLastCommitRequestValidationError) ErrorName() string {
	return "GetModelLastCommitRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetModelLastCommitRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetModelLastCommitRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetModelLastCommitRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetModelLastCommitRequestValidationError{}

// Validate checks the field values on GetModelLastCommitResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetModelLastCommitResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetModelLastCommitResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetModelLastCommitResponseMultiError, or nil if none found.
func (m *GetModelLastCommitResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetModelLastCommitResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Message

	// no validation rules for AuthorName

	// no validation rules for AuthorEmail

	// no validation rules for CreatedAt

	if len(errors) > 0 {
		return GetModelLastCommitResponseMultiError(errors)
	}

	return nil
}

// GetModelLastCommitResponseMultiError is an error wrapping multiple
// validation errors returned by GetModelLastCommitResponse.ValidateAll() if
// the designated constraints aren't met.
type GetModelLastCommitResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetModelLastCommitResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetModelLastCommitResponseMultiError) AllErrors() []error { return m }

// GetModelLastCommitResponseValidationError is the validation error returned
// by GetModelLastCommitResponse.Validate if the designated constraints aren't met.
type GetModelLastCommitResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetModelLastCommitResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetModelLastCommitResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetModelLastCommitResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetModelLastCommitResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetModelLastCommitResponseValidationError) ErrorName() string {
	return "GetModelLastCommitResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetModelLastCommitResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetModelLastCommitResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetModelLastCommitResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetModelLastCommitResponseValidationError{}

// Validate checks the field values on GetModelCommitRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetModelCommitRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetModelCommitRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetModelCommitRequestMultiError, or nil if none found.
func (m *GetModelCommitRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetModelCommitRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetProject()) < 1 {
		err := GetModelCommitRequestValidationError{
			field:  "Project",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetModelName()) < 1 {
		err := GetModelCommitRequestValidationError{
			field:  "ModelName",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetCommitId()) < 1 {
		err := GetModelCommitRequestValidationError{
			field:  "CommitId",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return GetModelCommitRequestMultiError(errors)
	}

	return nil
}

// GetModelCommitRequestMultiError is an error wrapping multiple validation
// errors returned by GetModelCommitRequest.ValidateAll() if the designated
// constraints aren't met.
type GetModelCommitRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetModelCommitRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetModelCommitRequestMultiError) AllErrors() []error { return m }

// GetModelCommitRequestValidationError is the validation error returned by
// GetModelCommitRequest.Validate if the designated constraints aren't met.
type GetModelCommitRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetModelCommitRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetModelCommitRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetModelCommitRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetModelCommitRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetModelCommitRequestValidationError) ErrorName() string {
	return "GetModelCommitRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetModelCommitRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetModelCommitRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetModelCommitRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetModelCommitRequestValidationError{}

// Validate checks the field values on GetModelCommitResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetModelCommitResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetModelCommitResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetModelCommitResponseMultiError, or nil if none found.
func (m *GetModelCommitResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetModelCommitResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Message

	// no validation rules for AuthorName

	// no validation rules for AuthorEmail

	// no validation rules for CreatedAt

	if len(errors) > 0 {
		return GetModelCommitResponseMultiError(errors)
	}

	return nil
}

// GetModelCommitResponseMultiError is an error wrapping multiple validation
// errors returned by GetModelCommitResponse.ValidateAll() if the designated
// constraints aren't met.
type GetModelCommitResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetModelCommitResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetModelCommitResponseMultiError) AllErrors() []error { return m }

// GetModelCommitResponseValidationError is the validation error returned by
// GetModelCommitResponse.Validate if the designated constraints aren't met.
type GetModelCommitResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetModelCommitResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetModelCommitResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetModelCommitResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetModelCommitResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetModelCommitResponseValidationError) ErrorName() string {
	return "GetModelCommitResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetModelCommitResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetModelCommitResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetModelCommitResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetModelCommitResponseValidationError{}

// Validate checks the field values on GetModelTreeCommitsRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetModelTreeCommitsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetModelTreeCommitsRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetModelTreeCommitsRequestMultiError, or nil if none found.
func (m *GetModelTreeCommitsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetModelTreeCommitsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetProject()) < 1 {
		err := GetModelTreeCommitsRequestValidationError{
			field:  "Project",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetModelName()) < 1 {
		err := GetModelTreeCommitsRequestValidationError{
			field:  "ModelName",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetRef()) < 1 {
		err := GetModelTreeCommitsRequestValidationError{
			field:  "Ref",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Path

	if len(errors) > 0 {
		return GetModelTreeCommitsRequestMultiError(errors)
	}

	return nil
}

// GetModelTreeCommitsRequestMultiError is an error wrapping multiple
// validation errors returned by GetModelTreeCommitsRequest.ValidateAll() if
// the designated constraints aren't met.
type GetModelTreeCommitsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetModelTreeCommitsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetModelTreeCommitsRequestMultiError) AllErrors() []error { return m }

// GetModelTreeCommitsRequestValidationError is the validation error returned
// by GetModelTreeCommitsRequest.Validate if the designated constraints aren't met.
type GetModelTreeCommitsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetModelTreeCommitsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetModelTreeCommitsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetModelTreeCommitsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetModelTreeCommitsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetModelTreeCommitsRequestValidationError) ErrorName() string {
	return "GetModelTreeCommitsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetModelTreeCommitsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetModelTreeCommitsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetModelTreeCommitsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetModelTreeCommitsRequestValidationError{}

// Validate checks the field values on GetModelTreeCommitsResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetModelTreeCommitsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetModelTreeCommitsResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetModelTreeCommitsResponseMultiError, or nil if none found.
func (m *GetModelTreeCommitsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetModelTreeCommitsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetItems() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetModelTreeCommitsResponseValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetModelTreeCommitsResponseValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetModelTreeCommitsResponseValidationError{
					field:  fmt.Sprintf("Items[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return GetModelTreeCommitsResponseMultiError(errors)
	}

	return nil
}

// GetModelTreeCommitsResponseMultiError is an error wrapping multiple
// validation errors returned by GetModelTreeCommitsResponse.ValidateAll() if
// the designated constraints aren't met.
type GetModelTreeCommitsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetModelTreeCommitsResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetModelTreeCommitsResponseMultiError) AllErrors() []error { return m }

// GetModelTreeCommitsResponseValidationError is the validation error returned
// by GetModelTreeCommitsResponse.Validate if the designated constraints
// aren't met.
type GetModelTreeCommitsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetModelTreeCommitsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetModelTreeCommitsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetModelTreeCommitsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetModelTreeCommitsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetModelTreeCommitsResponseValidationError) ErrorName() string {
	return "GetModelTreeCommitsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetModelTreeCommitsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetModelTreeCommitsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetModelTreeCommitsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetModelTreeCommitsResponseValidationError{}

// Validate checks the field values on GetModelTreeRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetModelTreeRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetModelTreeRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetModelTreeRequestMultiError, or nil if none found.
func (m *GetModelTreeRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetModelTreeRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetProject()) < 1 {
		err := GetModelTreeRequestValidationError{
			field:  "Project",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetModelName()) < 1 {
		err := GetModelTreeRequestValidationError{
			field:  "ModelName",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Ref

	if len(errors) > 0 {
		return GetModelTreeRequestMultiError(errors)
	}

	return nil
}

// GetModelTreeRequestMultiError is an error wrapping multiple validation
// errors returned by GetModelTreeRequest.ValidateAll() if the designated
// constraints aren't met.
type GetModelTreeRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetModelTreeRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetModelTreeRequestMultiError) AllErrors() []error { return m }

// GetModelTreeRequestValidationError is the validation error returned by
// GetModelTreeRequest.Validate if the designated constraints aren't met.
type GetModelTreeRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetModelTreeRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetModelTreeRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetModelTreeRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetModelTreeRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetModelTreeRequestValidationError) ErrorName() string {
	return "GetModelTreeRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetModelTreeRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetModelTreeRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetModelTreeRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetModelTreeRequestValidationError{}

// Validate checks the field values on GetModelTreeResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetModelTreeResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetModelTreeResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetModelTreeResponseMultiError, or nil if none found.
func (m *GetModelTreeResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetModelTreeResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetItems() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetModelTreeResponseValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetModelTreeResponseValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetModelTreeResponseValidationError{
					field:  fmt.Sprintf("Items[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return GetModelTreeResponseMultiError(errors)
	}

	return nil
}

// GetModelTreeResponseMultiError is an error wrapping multiple validation
// errors returned by GetModelTreeResponse.ValidateAll() if the designated
// constraints aren't met.
type GetModelTreeResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetModelTreeResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetModelTreeResponseMultiError) AllErrors() []error { return m }

// GetModelTreeResponseValidationError is the validation error returned by
// GetModelTreeResponse.Validate if the designated constraints aren't met.
type GetModelTreeResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetModelTreeResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetModelTreeResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetModelTreeResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetModelTreeResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetModelTreeResponseValidationError) ErrorName() string {
	return "GetModelTreeResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetModelTreeResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetModelTreeResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetModelTreeResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetModelTreeResponseValidationError{}

// Validate checks the field values on GetModelBlobRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetModelBlobRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetModelBlobRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetModelBlobRequestMultiError, or nil if none found.
func (m *GetModelBlobRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetModelBlobRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetProject()) < 1 {
		err := GetModelBlobRequestValidationError{
			field:  "Project",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetModelName()) < 1 {
		err := GetModelBlobRequestValidationError{
			field:  "ModelName",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Ref

	// no validation rules for Path

	if len(errors) > 0 {
		return GetModelBlobRequestMultiError(errors)
	}

	return nil
}

// GetModelBlobRequestMultiError is an error wrapping multiple validation
// errors returned by GetModelBlobRequest.ValidateAll() if the designated
// constraints aren't met.
type GetModelBlobRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetModelBlobRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetModelBlobRequestMultiError) AllErrors() []error { return m }

// GetModelBlobRequestValidationError is the validation error returned by
// GetModelBlobRequest.Validate if the designated constraints aren't met.
type GetModelBlobRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetModelBlobRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetModelBlobRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetModelBlobRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetModelBlobRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetModelBlobRequestValidationError) ErrorName() string {
	return "GetModelBlobRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetModelBlobRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetModelBlobRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetModelBlobRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetModelBlobRequestValidationError{}

// Validate checks the field values on GetModelBlobResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetModelBlobResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetModelBlobResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetModelBlobResponseMultiError, or nil if none found.
func (m *GetModelBlobResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetModelBlobResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Name

	// no validation rules for Type

	// no validation rules for Size

	// no validation rules for Path

	// no validation rules for Sha

	// no validation rules for Lfs

	// no validation rules for Content

	if len(errors) > 0 {
		return GetModelBlobResponseMultiError(errors)
	}

	return nil
}

// GetModelBlobResponseMultiError is an error wrapping multiple validation
// errors returned by GetModelBlobResponse.ValidateAll() if the designated
// constraints aren't met.
type GetModelBlobResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetModelBlobResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetModelBlobResponseMultiError) AllErrors() []error { return m }

// GetModelBlobResponseValidationError is the validation error returned by
// GetModelBlobResponse.Validate if the designated constraints aren't met.
type GetModelBlobResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetModelBlobResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetModelBlobResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetModelBlobResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetModelBlobResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetModelBlobResponseValidationError) ErrorName() string {
	return "GetModelBlobResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetModelBlobResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetModelBlobResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetModelBlobResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetModelBlobResponseValidationError{}

// Validate checks the field values on Model with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Model) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Model with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in ModelMultiError, or nil if none found.
func (m *Model) ValidateAll() error {
	return m.validate(true)
}

func (m *Model) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Name

	// no validation rules for Nickname

	// no validation rules for DefaultBranch

	// no validation rules for CreatedAt

	// no validation rules for UpdatedAt

	if all {
		switch v := interface{}(m.GetCloneUrls()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ModelValidationError{
					field:  "CloneUrls",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ModelValidationError{
					field:  "CloneUrls",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCloneUrls()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ModelValidationError{
				field:  "CloneUrls",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	for idx, item := range m.GetTags() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ModelValidationError{
						field:  fmt.Sprintf("Tags[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ModelValidationError{
						field:  fmt.Sprintf("Tags[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ModelValidationError{
					field:  fmt.Sprintf("Tags[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ModelMultiError(errors)
	}

	return nil
}

// ModelMultiError is an error wrapping multiple validation errors returned by
// Model.ValidateAll() if the designated constraints aren't met.
type ModelMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ModelMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ModelMultiError) AllErrors() []error { return m }

// ModelValidationError is the validation error returned by Model.Validate if
// the designated constraints aren't met.
type ModelValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ModelValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ModelValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ModelValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ModelValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ModelValidationError) ErrorName() string { return "ModelValidationError" }

// Error satisfies the builtin error interface
func (e ModelValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sModel.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ModelValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ModelValidationError{}

// Validate checks the field values on CloneUrls with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *CloneUrls) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CloneUrls with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in CloneUrlsMultiError, or nil
// if none found.
func (m *CloneUrls) ValidateAll() error {
	return m.validate(true)
}

func (m *CloneUrls) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for SshUrl

	// no validation rules for HttpUrl

	if len(errors) > 0 {
		return CloneUrlsMultiError(errors)
	}

	return nil
}

// CloneUrlsMultiError is an error wrapping multiple validation errors returned
// by CloneUrls.ValidateAll() if the designated constraints aren't met.
type CloneUrlsMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CloneUrlsMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CloneUrlsMultiError) AllErrors() []error { return m }

// CloneUrlsValidationError is the validation error returned by
// CloneUrls.Validate if the designated constraints aren't met.
type CloneUrlsValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CloneUrlsValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CloneUrlsValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CloneUrlsValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CloneUrlsValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CloneUrlsValidationError) ErrorName() string { return "CloneUrlsValidationError" }

// Error satisfies the builtin error interface
func (e CloneUrlsValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCloneUrls.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CloneUrlsValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CloneUrlsValidationError{}

// Validate checks the field values on Label with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Label) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Label with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in LabelMultiError, or nil if none found.
func (m *Label) ValidateAll() error {
	return m.validate(true)
}

func (m *Label) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Name

	// no validation rules for CreatedAt

	// no validation rules for UpdatedAt

	if len(errors) > 0 {
		return LabelMultiError(errors)
	}

	return nil
}

// LabelMultiError is an error wrapping multiple validation errors returned by
// Label.ValidateAll() if the designated constraints aren't met.
type LabelMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m LabelMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m LabelMultiError) AllErrors() []error { return m }

// LabelValidationError is the validation error returned by Label.Validate if
// the designated constraints aren't met.
type LabelValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e LabelValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e LabelValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e LabelValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e LabelValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e LabelValidationError) ErrorName() string { return "LabelValidationError" }

// Error satisfies the builtin error interface
func (e LabelValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sLabel.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = LabelValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = LabelValidationError{}

// Validate checks the field values on Branch with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Branch) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Branch with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in BranchMultiError, or nil if none found.
func (m *Branch) ValidateAll() error {
	return m.validate(true)
}

func (m *Branch) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Name

	// no validation rules for Message

	if len(errors) > 0 {
		return BranchMultiError(errors)
	}

	return nil
}

// BranchMultiError is an error wrapping multiple validation errors returned by
// Branch.ValidateAll() if the designated constraints aren't met.
type BranchMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BranchMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BranchMultiError) AllErrors() []error { return m }

// BranchValidationError is the validation error returned by Branch.Validate if
// the designated constraints aren't met.
type BranchValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BranchValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BranchValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BranchValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BranchValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BranchValidationError) ErrorName() string { return "BranchValidationError" }

// Error satisfies the builtin error interface
func (e BranchValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBranch.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BranchValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BranchValidationError{}

// Validate checks the field values on Tag with the rules defined in the proto
// definition for this message. If any rules are violated, the first error
// encountered is returned, or nil if there are no violations.
func (m *Tag) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Tag with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in TagMultiError, or nil if none found.
func (m *Tag) ValidateAll() error {
	return m.validate(true)
}

func (m *Tag) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Name

	if len(errors) > 0 {
		return TagMultiError(errors)
	}

	return nil
}

// TagMultiError is an error wrapping multiple validation errors returned by
// Tag.ValidateAll() if the designated constraints aren't met.
type TagMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TagMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TagMultiError) AllErrors() []error { return m }

// TagValidationError is the validation error returned by Tag.Validate if the
// designated constraints aren't met.
type TagValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TagValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TagValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TagValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TagValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TagValidationError) ErrorName() string { return "TagValidationError" }

// Error satisfies the builtin error interface
func (e TagValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTag.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TagValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TagValidationError{}
