// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: v1alpha1/model.proto

package v1alpha1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileType int32

const (
	FileType_DIR  FileType = 0
	FileType_FILE FileType = 1
)

// Enum value maps for FileType.
var (
	FileType_name = map[int32]string{
		0: "DIR",
		1: "FILE",
	}
	FileType_value = map[string]int32{
		"DIR":  0,
		"FILE": 1,
	}
)

func (x FileType) Enum() *FileType {
	p := new(FileType)
	*p = x
	return p
}

func (x FileType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FileType) Descriptor() protoreflect.EnumDescriptor {
	return file_v1alpha1_model_proto_enumTypes[0].Descriptor()
}

func (FileType) Type() protoreflect.EnumType {
	return &file_v1alpha1_model_proto_enumTypes[0]
}

func (x FileType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FileType.Descriptor instead.
func (FileType) EnumDescriptor() ([]byte, []int) {
	return file_v1alpha1_model_proto_rawDescGZIP(), []int{0}
}

type ListModelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Search        string                 `protobuf:"bytes,2,opt,name=search,proto3" json:"search,omitempty"`
	Sort          string                 `protobuf:"bytes,3,opt,name=sort,proto3" json:"sort,omitempty"`
	Page          int32                  `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelsRequest) Reset() {
	*x = ListModelsRequest{}
	mi := &file_v1alpha1_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsRequest) ProtoMessage() {}

func (x *ListModelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsRequest.ProtoReflect.Descriptor instead.
func (*ListModelsRequest) Descriptor() ([]byte, []int) {
	return file_v1alpha1_model_proto_rawDescGZIP(), []int{0}
}

func (x *ListModelsRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *ListModelsRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *ListModelsRequest) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

func (x *ListModelsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListModelsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListModelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          []*Model               `protobuf:"bytes,1,rep,name=item,proto3" json:"item,omitempty"`
	Pagination    *Pagination            `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelsResponse) Reset() {
	*x = ListModelsResponse{}
	mi := &file_v1alpha1_model_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsResponse) ProtoMessage() {}

func (x *ListModelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_model_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsResponse.ProtoReflect.Descriptor instead.
func (*ListModelsResponse) Descriptor() ([]byte, []int) {
	return file_v1alpha1_model_proto_rawDescGZIP(), []int{1}
}

func (x *ListModelsResponse) GetItem() []*Model {
	if x != nil {
		return x.Item
	}
	return nil
}

func (x *ListModelsResponse) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type GetModelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       string                 `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	ModelName     string                 `protobuf:"bytes,2,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModelRequest) Reset() {
	*x = GetModelRequest{}
	mi := &file_v1alpha1_model_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModelRequest) ProtoMessage() {}

func (x *GetModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_model_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModelRequest.ProtoReflect.Descriptor instead.
func (*GetModelRequest) Descriptor() ([]byte, []int) {
	return file_v1alpha1_model_proto_rawDescGZIP(), []int{2}
}

func (x *GetModelRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *GetModelRequest) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

type GetModelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         *Model                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModelResponse) Reset() {
	*x = GetModelResponse{}
	mi := &file_v1alpha1_model_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModelResponse) ProtoMessage() {}

func (x *GetModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_model_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModelResponse.ProtoReflect.Descriptor instead.
func (*GetModelResponse) Descriptor() ([]byte, []int) {
	return file_v1alpha1_model_proto_rawDescGZIP(), []int{3}
}

func (x *GetModelResponse) GetModel() *Model {
	if x != nil {
		return x.Model
	}
	return nil
}

type CreateModelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       string                 `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	ModelName     string                 `protobuf:"bytes,2,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateModelRequest) Reset() {
	*x = CreateModelRequest{}
	mi := &file_v1alpha1_model_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateModelRequest) ProtoMessage() {}

func (x *CreateModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_model_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateModelRequest.ProtoReflect.Descriptor instead.
func (*CreateModelRequest) Descriptor() ([]byte, []int) {
	return file_v1alpha1_model_proto_rawDescGZIP(), []int{4}
}

func (x *CreateModelRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *CreateModelRequest) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

type CreateModelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateModelResponse) Reset() {
	*x = CreateModelResponse{}
	mi := &file_v1alpha1_model_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateModelResponse) ProtoMessage() {}

func (x *CreateModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_model_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateModelResponse.ProtoReflect.Descriptor instead.
func (*CreateModelResponse) Descriptor() ([]byte, []int) {
	return file_v1alpha1_model_proto_rawDescGZIP(), []int{5}
}

type DeleteModelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       string                 `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	ModelName     string                 `protobuf:"bytes,2,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteModelRequest) Reset() {
	*x = DeleteModelRequest{}
	mi := &file_v1alpha1_model_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteModelRequest) ProtoMessage() {}

func (x *DeleteModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_model_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteModelRequest.ProtoReflect.Descriptor instead.
func (*DeleteModelRequest) Descriptor() ([]byte, []int) {
	return file_v1alpha1_model_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteModelRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *DeleteModelRequest) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

type DeleteModelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteModelResponse) Reset() {
	*x = DeleteModelResponse{}
	mi := &file_v1alpha1_model_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteModelResponse) ProtoMessage() {}

func (x *DeleteModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_model_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteModelResponse.ProtoReflect.Descriptor instead.
func (*DeleteModelResponse) Descriptor() ([]byte, []int) {
	return file_v1alpha1_model_proto_rawDescGZIP(), []int{7}
}

type ListModelBranchesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       string                 `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	ModelName     string                 `protobuf:"bytes,2,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelBranchesRequest) Reset() {
	*x = ListModelBranchesRequest{}
	mi := &file_v1alpha1_model_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelBranchesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelBranchesRequest) ProtoMessage() {}

func (x *ListModelBranchesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_model_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelBranchesRequest.ProtoReflect.Descriptor instead.
func (*ListModelBranchesRequest) Descriptor() ([]byte, []int) {
	return file_v1alpha1_model_proto_rawDescGZIP(), []int{8}
}

func (x *ListModelBranchesRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *ListModelBranchesRequest) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *ListModelBranchesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListModelBranchesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListModelBranchesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Branch              `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelBranchesResponse) Reset() {
	*x = ListModelBranchesResponse{}
	mi := &file_v1alpha1_model_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelBranchesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelBranchesResponse) ProtoMessage() {}

func (x *ListModelBranchesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_model_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelBranchesResponse.ProtoReflect.Descriptor instead.
func (*ListModelBranchesResponse) Descriptor() ([]byte, []int) {
	return file_v1alpha1_model_proto_rawDescGZIP(), []int{9}
}

func (x *ListModelBranchesResponse) GetItems() []*Branch {
	if x != nil {
		return x.Items
	}
	return nil
}

type ListModelTagsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       string                 `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	ModelName     string                 `protobuf:"bytes,2,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelTagsRequest) Reset() {
	*x = ListModelTagsRequest{}
	mi := &file_v1alpha1_model_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelTagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelTagsRequest) ProtoMessage() {}

func (x *ListModelTagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_model_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelTagsRequest.ProtoReflect.Descriptor instead.
func (*ListModelTagsRequest) Descriptor() ([]byte, []int) {
	return file_v1alpha1_model_proto_rawDescGZIP(), []int{10}
}

func (x *ListModelTagsRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *ListModelTagsRequest) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *ListModelTagsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListModelTagsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListModelTagsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Label               `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelTagsResponse) Reset() {
	*x = ListModelTagsResponse{}
	mi := &file_v1alpha1_model_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelTagsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelTagsResponse) ProtoMessage() {}

func (x *ListModelTagsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_model_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelTagsResponse.ProtoReflect.Descriptor instead.
func (*ListModelTagsResponse) Descriptor() ([]byte, []int) {
	return file_v1alpha1_model_proto_rawDescGZIP(), []int{11}
}

func (x *ListModelTagsResponse) GetItems() []*Label {
	if x != nil {
		return x.Items
	}
	return nil
}

type GetModelLastCommitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       string                 `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	ModelName     string                 `protobuf:"bytes,2,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModelLastCommitRequest) Reset() {
	*x = GetModelLastCommitRequest{}
	mi := &file_v1alpha1_model_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModelLastCommitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModelLastCommitRequest) ProtoMessage() {}

func (x *GetModelLastCommitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_model_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModelLastCommitRequest.ProtoReflect.Descriptor instead.
func (*GetModelLastCommitRequest) Descriptor() ([]byte, []int) {
	return file_v1alpha1_model_proto_rawDescGZIP(), []int{12}
}

func (x *GetModelLastCommitRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *GetModelLastCommitRequest) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

type GetModelLastCommitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	AuthorName    string                 `protobuf:"bytes,3,opt,name=author_name,json=authorName,proto3" json:"author_name,omitempty"`
	AuthorEmail   string                 `protobuf:"bytes,4,opt,name=author_email,json=authorEmail,proto3" json:"author_email,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModelLastCommitResponse) Reset() {
	*x = GetModelLastCommitResponse{}
	mi := &file_v1alpha1_model_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModelLastCommitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModelLastCommitResponse) ProtoMessage() {}

func (x *GetModelLastCommitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_model_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModelLastCommitResponse.ProtoReflect.Descriptor instead.
func (*GetModelLastCommitResponse) Descriptor() ([]byte, []int) {
	return file_v1alpha1_model_proto_rawDescGZIP(), []int{13}
}

func (x *GetModelLastCommitResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetModelLastCommitResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetModelLastCommitResponse) GetAuthorName() string {
	if x != nil {
		return x.AuthorName
	}
	return ""
}

func (x *GetModelLastCommitResponse) GetAuthorEmail() string {
	if x != nil {
		return x.AuthorEmail
	}
	return ""
}

func (x *GetModelLastCommitResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type GetModelCommitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       string                 `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	ModelName     string                 `protobuf:"bytes,2,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	CommitId      string                 `protobuf:"bytes,3,opt,name=commit_id,json=commitId,proto3" json:"commit_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModelCommitRequest) Reset() {
	*x = GetModelCommitRequest{}
	mi := &file_v1alpha1_model_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModelCommitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModelCommitRequest) ProtoMessage() {}

func (x *GetModelCommitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_model_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModelCommitRequest.ProtoReflect.Descriptor instead.
func (*GetModelCommitRequest) Descriptor() ([]byte, []int) {
	return file_v1alpha1_model_proto_rawDescGZIP(), []int{14}
}

func (x *GetModelCommitRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *GetModelCommitRequest) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *GetModelCommitRequest) GetCommitId() string {
	if x != nil {
		return x.CommitId
	}
	return ""
}

type GetModelCommitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	AuthorName    string                 `protobuf:"bytes,3,opt,name=author_name,json=authorName,proto3" json:"author_name,omitempty"`
	AuthorEmail   string                 `protobuf:"bytes,4,opt,name=author_email,json=authorEmail,proto3" json:"author_email,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModelCommitResponse) Reset() {
	*x = GetModelCommitResponse{}
	mi := &file_v1alpha1_model_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModelCommitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModelCommitResponse) ProtoMessage() {}

func (x *GetModelCommitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_model_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModelCommitResponse.ProtoReflect.Descriptor instead.
func (*GetModelCommitResponse) Descriptor() ([]byte, []int) {
	return file_v1alpha1_model_proto_rawDescGZIP(), []int{15}
}

func (x *GetModelCommitResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetModelCommitResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetModelCommitResponse) GetAuthorName() string {
	if x != nil {
		return x.AuthorName
	}
	return ""
}

func (x *GetModelCommitResponse) GetAuthorEmail() string {
	if x != nil {
		return x.AuthorEmail
	}
	return ""
}

func (x *GetModelCommitResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type GetModelTreeCommitsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       string                 `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	ModelName     string                 `protobuf:"bytes,2,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	Ref           string                 `protobuf:"bytes,3,opt,name=ref,proto3" json:"ref,omitempty"`
	Path          string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModelTreeCommitsRequest) Reset() {
	*x = GetModelTreeCommitsRequest{}
	mi := &file_v1alpha1_model_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModelTreeCommitsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModelTreeCommitsRequest) ProtoMessage() {}

func (x *GetModelTreeCommitsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_model_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModelTreeCommitsRequest.ProtoReflect.Descriptor instead.
func (*GetModelTreeCommitsRequest) Descriptor() ([]byte, []int) {
	return file_v1alpha1_model_proto_rawDescGZIP(), []int{16}
}

func (x *GetModelTreeCommitsRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *GetModelTreeCommitsRequest) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *GetModelTreeCommitsRequest) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

func (x *GetModelTreeCommitsRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type GetModelTreeCommitsResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Items         []*GetModelCommitResponse `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModelTreeCommitsResponse) Reset() {
	*x = GetModelTreeCommitsResponse{}
	mi := &file_v1alpha1_model_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModelTreeCommitsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModelTreeCommitsResponse) ProtoMessage() {}

func (x *GetModelTreeCommitsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_model_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModelTreeCommitsResponse.ProtoReflect.Descriptor instead.
func (*GetModelTreeCommitsResponse) Descriptor() ([]byte, []int) {
	return file_v1alpha1_model_proto_rawDescGZIP(), []int{17}
}

func (x *GetModelTreeCommitsResponse) GetItems() []*GetModelCommitResponse {
	if x != nil {
		return x.Items
	}
	return nil
}

type GetModelTreeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       string                 `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	ModelName     string                 `protobuf:"bytes,2,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	Ref           string                 `protobuf:"bytes,3,opt,name=ref,proto3" json:"ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModelTreeRequest) Reset() {
	*x = GetModelTreeRequest{}
	mi := &file_v1alpha1_model_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModelTreeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModelTreeRequest) ProtoMessage() {}

func (x *GetModelTreeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_model_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModelTreeRequest.ProtoReflect.Descriptor instead.
func (*GetModelTreeRequest) Descriptor() ([]byte, []int) {
	return file_v1alpha1_model_proto_rawDescGZIP(), []int{18}
}

func (x *GetModelTreeRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *GetModelTreeRequest) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *GetModelTreeRequest) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

type GetModelTreeResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Items         []*GetModelBlobResponse `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModelTreeResponse) Reset() {
	*x = GetModelTreeResponse{}
	mi := &file_v1alpha1_model_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModelTreeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModelTreeResponse) ProtoMessage() {}

func (x *GetModelTreeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_model_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModelTreeResponse.ProtoReflect.Descriptor instead.
func (*GetModelTreeResponse) Descriptor() ([]byte, []int) {
	return file_v1alpha1_model_proto_rawDescGZIP(), []int{19}
}

func (x *GetModelTreeResponse) GetItems() []*GetModelBlobResponse {
	if x != nil {
		return x.Items
	}
	return nil
}

type GetModelBlobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       string                 `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	ModelName     string                 `protobuf:"bytes,2,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	Ref           string                 `protobuf:"bytes,3,opt,name=ref,proto3" json:"ref,omitempty"`
	Path          string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModelBlobRequest) Reset() {
	*x = GetModelBlobRequest{}
	mi := &file_v1alpha1_model_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModelBlobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModelBlobRequest) ProtoMessage() {}

func (x *GetModelBlobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_model_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModelBlobRequest.ProtoReflect.Descriptor instead.
func (*GetModelBlobRequest) Descriptor() ([]byte, []int) {
	return file_v1alpha1_model_proto_rawDescGZIP(), []int{20}
}

func (x *GetModelBlobRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *GetModelBlobRequest) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *GetModelBlobRequest) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

func (x *GetModelBlobRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type GetModelBlobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          FileType               `protobuf:"varint,2,opt,name=type,proto3,enum=matrixhub.v1alpha1.FileType" json:"type,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Path          string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	Sha           string                 `protobuf:"bytes,5,opt,name=sha,proto3" json:"sha,omitempty"`
	Lfs           bool                   `protobuf:"varint,6,opt,name=lfs,proto3" json:"lfs,omitempty"`
	Content       string                 `protobuf:"bytes,7,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModelBlobResponse) Reset() {
	*x = GetModelBlobResponse{}
	mi := &file_v1alpha1_model_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModelBlobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModelBlobResponse) ProtoMessage() {}

func (x *GetModelBlobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_model_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModelBlobResponse.ProtoReflect.Descriptor instead.
func (*GetModelBlobResponse) Descriptor() ([]byte, []int) {
	return file_v1alpha1_model_proto_rawDescGZIP(), []int{21}
}

func (x *GetModelBlobResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetModelBlobResponse) GetType() FileType {
	if x != nil {
		return x.Type
	}
	return FileType_DIR
}

func (x *GetModelBlobResponse) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *GetModelBlobResponse) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *GetModelBlobResponse) GetSha() string {
	if x != nil {
		return x.Sha
	}
	return ""
}

func (x *GetModelBlobResponse) GetLfs() bool {
	if x != nil {
		return x.Lfs
	}
	return false
}

func (x *GetModelBlobResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type Model struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Nickname      string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	DefaultBranch string                 `protobuf:"bytes,4,opt,name=default_branch,json=defaultBranch,proto3" json:"default_branch,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CloneUrls     *CloneUrls             `protobuf:"bytes,7,opt,name=clone_urls,json=cloneUrls,proto3" json:"clone_urls,omitempty"`
	Tags          []*Tag                 `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Model) Reset() {
	*x = Model{}
	mi := &file_v1alpha1_model_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Model) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Model) ProtoMessage() {}

func (x *Model) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_model_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Model.ProtoReflect.Descriptor instead.
func (*Model) Descriptor() ([]byte, []int) {
	return file_v1alpha1_model_proto_rawDescGZIP(), []int{22}
}

func (x *Model) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Model) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Model) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *Model) GetDefaultBranch() string {
	if x != nil {
		return x.DefaultBranch
	}
	return ""
}

func (x *Model) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Model) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Model) GetCloneUrls() *CloneUrls {
	if x != nil {
		return x.CloneUrls
	}
	return nil
}

func (x *Model) GetTags() []*Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

type CloneUrls struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SshUrl        string                 `protobuf:"bytes,1,opt,name=ssh_url,json=sshUrl,proto3" json:"ssh_url,omitempty"`
	HttpUrl       string                 `protobuf:"bytes,2,opt,name=http_url,json=httpUrl,proto3" json:"http_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloneUrls) Reset() {
	*x = CloneUrls{}
	mi := &file_v1alpha1_model_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloneUrls) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloneUrls) ProtoMessage() {}

func (x *CloneUrls) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_model_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloneUrls.ProtoReflect.Descriptor instead.
func (*CloneUrls) Descriptor() ([]byte, []int) {
	return file_v1alpha1_model_proto_rawDescGZIP(), []int{23}
}

func (x *CloneUrls) GetSshUrl() string {
	if x != nil {
		return x.SshUrl
	}
	return ""
}

func (x *CloneUrls) GetHttpUrl() string {
	if x != nil {
		return x.HttpUrl
	}
	return ""
}

type Label struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Label) Reset() {
	*x = Label{}
	mi := &file_v1alpha1_model_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Label) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Label) ProtoMessage() {}

func (x *Label) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_model_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Label.ProtoReflect.Descriptor instead.
func (*Label) Descriptor() ([]byte, []int) {
	return file_v1alpha1_model_proto_rawDescGZIP(), []int{24}
}

func (x *Label) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Label) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Label) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Label) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type Branch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Branch) Reset() {
	*x = Branch{}
	mi := &file_v1alpha1_model_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Branch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Branch) ProtoMessage() {}

func (x *Branch) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_model_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Branch.ProtoReflect.Descriptor instead.
func (*Branch) Descriptor() ([]byte, []int) {
	return file_v1alpha1_model_proto_rawDescGZIP(), []int{25}
}

func (x *Branch) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Branch) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Tag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tag) Reset() {
	*x = Tag{}
	mi := &file_v1alpha1_model_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tag) ProtoMessage() {}

func (x *Tag) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_model_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tag.ProtoReflect.Descriptor instead.
func (*Tag) Descriptor() ([]byte, []int) {
	return file_v1alpha1_model_proto_rawDescGZIP(), []int{26}
}

func (x *Tag) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_v1alpha1_model_proto protoreflect.FileDescriptor

const file_v1alpha1_model_proto_rawDesc = "" +
	"\n" +
	"\x14v1alpha1/model.proto\x12\x12matrixhub.v1alpha1\x1a\x1cgoogle/api/annotations.proto\x1a\x17validate/validate.proto\x1a\x14v1alpha1/utils.proto\"\x86\x01\n" +
	"\x11ListModelsRequest\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x16\n" +
	"\x06search\x18\x02 \x01(\tR\x06search\x12\x12\n" +
	"\x04sort\x18\x03 \x01(\tR\x04sort\x12\x12\n" +
	"\x04page\x18\x04 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x05 \x01(\x05R\bpageSize\"\x83\x01\n" +
	"\x12ListModelsResponse\x12-\n" +
	"\x04item\x18\x01 \x03(\v2\x19.matrixhub.v1alpha1.ModelR\x04item\x12>\n" +
	"\n" +
	"pagination\x18\x03 \x01(\v2\x1e.matrixhub.v1alpha1.PaginationR\n" +
	"pagination\"\\\n" +
	"\x0fGetModelRequest\x12!\n" +
	"\aproject\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\aproject\x12&\n" +
	"\n" +
	"model_name\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\tmodelName\"C\n" +
	"\x10GetModelResponse\x12/\n" +
	"\x05model\x18\x01 \x01(\v2\x19.matrixhub.v1alpha1.ModelR\x05model\"_\n" +
	"\x12CreateModelRequest\x12!\n" +
	"\aproject\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\aproject\x12&\n" +
	"\n" +
	"model_name\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\tmodelName\"\x15\n" +
	"\x13CreateModelResponse\"_\n" +
	"\x12DeleteModelRequest\x12!\n" +
	"\aproject\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\aproject\x12&\n" +
	"\n" +
	"model_name\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\tmodelName\"\x15\n" +
	"\x13DeleteModelResponse\"\x96\x01\n" +
	"\x18ListModelBranchesRequest\x12!\n" +
	"\aproject\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\aproject\x12&\n" +
	"\n" +
	"model_name\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\tmodelName\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"M\n" +
	"\x19ListModelBranchesResponse\x120\n" +
	"\x05items\x18\x01 \x03(\v2\x1a.matrixhub.v1alpha1.BranchR\x05items\"\x92\x01\n" +
	"\x14ListModelTagsRequest\x12!\n" +
	"\aproject\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\aproject\x12&\n" +
	"\n" +
	"model_name\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\tmodelName\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"H\n" +
	"\x15ListModelTagsResponse\x12/\n" +
	"\x05items\x18\x01 \x03(\v2\x19.matrixhub.v1alpha1.LabelR\x05items\"f\n" +
	"\x19GetModelLastCommitRequest\x12!\n" +
	"\aproject\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\aproject\x12&\n" +
	"\n" +
	"model_name\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\tmodelName\"\xa9\x01\n" +
	"\x1aGetModelLastCommitResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1f\n" +
	"\vauthor_name\x18\x03 \x01(\tR\n" +
	"authorName\x12!\n" +
	"\fauthor_email\x18\x04 \x01(\tR\vauthorEmail\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\"\x88\x01\n" +
	"\x15GetModelCommitRequest\x12!\n" +
	"\aproject\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\aproject\x12&\n" +
	"\n" +
	"model_name\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\tmodelName\x12$\n" +
	"\tcommit_id\x18\x03 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\bcommitId\"\xa5\x01\n" +
	"\x16GetModelCommitResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1f\n" +
	"\vauthor_name\x18\x03 \x01(\tR\n" +
	"authorName\x12!\n" +
	"\fauthor_email\x18\x04 \x01(\tR\vauthorEmail\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\"\x96\x01\n" +
	"\x1aGetModelTreeCommitsRequest\x12!\n" +
	"\aproject\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\aproject\x12&\n" +
	"\n" +
	"model_name\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\tmodelName\x12\x19\n" +
	"\x03ref\x18\x03 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x03ref\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\"_\n" +
	"\x1bGetModelTreeCommitsResponse\x12@\n" +
	"\x05items\x18\x01 \x03(\v2*.matrixhub.v1alpha1.GetModelCommitResponseR\x05items\"r\n" +
	"\x13GetModelTreeRequest\x12!\n" +
	"\aproject\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\aproject\x12&\n" +
	"\n" +
	"model_name\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\tmodelName\x12\x10\n" +
	"\x03ref\x18\x03 \x01(\tR\x03ref\"V\n" +
	"\x14GetModelTreeResponse\x12>\n" +
	"\x05items\x18\x01 \x03(\v2(.matrixhub.v1alpha1.GetModelBlobResponseR\x05items\"\x86\x01\n" +
	"\x13GetModelBlobRequest\x12!\n" +
	"\aproject\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\aproject\x12&\n" +
	"\n" +
	"model_name\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\tmodelName\x12\x10\n" +
	"\x03ref\x18\x03 \x01(\tR\x03ref\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\"\xc2\x01\n" +
	"\x14GetModelBlobResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x120\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1c.matrixhub.v1alpha1.FileTypeR\x04type\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x12\x10\n" +
	"\x03sha\x18\x05 \x01(\tR\x03sha\x12\x10\n" +
	"\x03lfs\x18\x06 \x01(\bR\x03lfs\x12\x18\n" +
	"\acontent\x18\a \x01(\tR\acontent\"\x97\x02\n" +
	"\x05Model\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\x12%\n" +
	"\x0edefault_branch\x18\x04 \x01(\tR\rdefaultBranch\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt\x12<\n" +
	"\n" +
	"clone_urls\x18\a \x01(\v2\x1d.matrixhub.v1alpha1.CloneUrlsR\tcloneUrls\x12+\n" +
	"\x04tags\x18\b \x03(\v2\x17.matrixhub.v1alpha1.TagR\x04tags\"?\n" +
	"\tCloneUrls\x12\x17\n" +
	"\assh_url\x18\x01 \x01(\tR\x06sshUrl\x12\x19\n" +
	"\bhttp_url\x18\x02 \x01(\tR\ahttpUrl\"i\n" +
	"\x05Label\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\tR\tupdatedAt\"6\n" +
	"\x06Branch\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\x19\n" +
	"\x03Tag\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name*\x1d\n" +
	"\bFileType\x12\a\n" +
	"\x03DIR\x10\x00\x12\b\n" +
	"\x04FILE\x10\x012\xb0\x0e\n" +
	"\x06Models\x12y\n" +
	"\n" +
	"ListModels\x12%.matrixhub.v1alpha1.ListModelsRequest\x1a&.matrixhub.v1alpha1.ListModelsResponse\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/api/v1alpha1/models\x12\x8a\x01\n" +
	"\bGetModel\x12#.matrixhub.v1alpha1.GetModelRequest\x1a$.matrixhub.v1alpha1.GetModelResponse\"3\x82\xd3\xe4\x93\x02-\x12+/api/v1alpha1/models/{project}/{model_name}\x12\x96\x01\n" +
	"\vCreateModel\x12&.matrixhub.v1alpha1.CreateModelRequest\x1a'.matrixhub.v1alpha1.CreateModelResponse\"6\x82\xd3\xe4\x93\x020:\x01*\"+/api/v1alpha1/models/{project}/{model_name}\x12\x93\x01\n" +
	"\vDeleteModel\x12&.matrixhub.v1alpha1.DeleteModelRequest\x1a'.matrixhub.v1alpha1.DeleteModelResponse\"3\x82\xd3\xe4\x93\x02-*+/api/v1alpha1/models/{project}/{model_name}\x12\xae\x01\n" +
	"\x11ListModelBranches\x12,.matrixhub.v1alpha1.ListModelBranchesRequest\x1a-.matrixhub.v1alpha1.ListModelBranchesResponse\"<\x82\xd3\xe4\x93\x026\x124/api/v1alpha1/models/{project}/{model_name}/branches\x12\x9e\x01\n" +
	"\rListModelTags\x12(.matrixhub.v1alpha1.ListModelTagsRequest\x1a).matrixhub.v1alpha1.ListModelTagsResponse\"8\x82\xd3\xe4\x93\x022\x120/api/v1alpha1/models/{project}/{model_name}/tags\x12\xb4\x01\n" +
	"\x12GetModelLastCommit\x12-.matrixhub.v1alpha1.GetModelLastCommitRequest\x1a..matrixhub.v1alpha1.GetModelLastCommitResponse\"?\x82\xd3\xe4\x93\x029\x127/api/v1alpha1/models/{project}/{model_name}/last_commit\x12\xb0\x01\n" +
	"\x0eGetModelCommit\x12).matrixhub.v1alpha1.GetModelCommitRequest\x1a*.matrixhub.v1alpha1.GetModelCommitResponse\"G\x82\xd3\xe4\x93\x02A\x12?/api/v1alpha1/models/{project}/{model_name}/commits/{commit_id}\x12\xd0\x01\n" +
	"\x13GetModelTreeCommits\x12..matrixhub.v1alpha1.GetModelTreeCommitsRequest\x1a/.matrixhub.v1alpha1.GetModelTreeCommitsResponse\"X\x82\xd3\xe4\x93\x02R\x12P/api/v1alpha1/models/{project}/{model_name}/refs/{ref=**}/tree_commits/{path=**}\x12\xa9\x01\n" +
	"\fGetModelTree\x12'.matrixhub.v1alpha1.GetModelTreeRequest\x1a(.matrixhub.v1alpha1.GetModelTreeResponse\"F\x82\xd3\xe4\x93\x02@\x12>/api/v1alpha1/models/{project}/{model_name}/refs/{ref=**}/tree\x12\xb3\x01\n" +
	"\fGetModelBlob\x12'.matrixhub.v1alpha1.GetModelBlobRequest\x1a(.matrixhub.v1alpha1.GetModelBlobResponse\"P\x82\xd3\xe4\x93\x02J\x12H/api/v1alpha1/models/{project}/{model_name}/refs/{ref=**}/blob/{path=**}B<Z:github.com/matrixhub-ai/matrixhub/api/go/v1alpha1;v1alpha1b\x06proto3"

var (
	file_v1alpha1_model_proto_rawDescOnce sync.Once
	file_v1alpha1_model_proto_rawDescData []byte
)

func file_v1alpha1_model_proto_rawDescGZIP() []byte {
	file_v1alpha1_model_proto_rawDescOnce.Do(func() {
		file_v1alpha1_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1alpha1_model_proto_rawDesc), len(file_v1alpha1_model_proto_rawDesc)))
	})
	return file_v1alpha1_model_proto_rawDescData
}

var file_v1alpha1_model_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1alpha1_model_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_v1alpha1_model_proto_goTypes = []any{
	(FileType)(0),                       // 0: matrixhub.v1alpha1.FileType
	(*ListModelsRequest)(nil),           // 1: matrixhub.v1alpha1.ListModelsRequest
	(*ListModelsResponse)(nil),          // 2: matrixhub.v1alpha1.ListModelsResponse
	(*GetModelRequest)(nil),             // 3: matrixhub.v1alpha1.GetModelRequest
	(*GetModelResponse)(nil),            // 4: matrixhub.v1alpha1.GetModelResponse
	(*CreateModelRequest)(nil),          // 5: matrixhub.v1alpha1.CreateModelRequest
	(*CreateModelResponse)(nil),         // 6: matrixhub.v1alpha1.CreateModelResponse
	(*DeleteModelRequest)(nil),          // 7: matrixhub.v1alpha1.DeleteModelRequest
	(*DeleteModelResponse)(nil),         // 8: matrixhub.v1alpha1.DeleteModelResponse
	(*ListModelBranchesRequest)(nil),    // 9: matrixhub.v1alpha1.ListModelBranchesRequest
	(*ListModelBranchesResponse)(nil),   // 10: matrixhub.v1alpha1.ListModelBranchesResponse
	(*ListModelTagsRequest)(nil),        // 11: matrixhub.v1alpha1.ListModelTagsRequest
	(*ListModelTagsResponse)(nil),       // 12: matrixhub.v1alpha1.ListModelTagsResponse
	(*GetModelLastCommitRequest)(nil),   // 13: matrixhub.v1alpha1.GetModelLastCommitRequest
	(*GetModelLastCommitResponse)(nil),  // 14: matrixhub.v1alpha1.GetModelLastCommitResponse
	(*GetModelCommitRequest)(nil),       // 15: matrixhub.v1alpha1.GetModelCommitRequest
	(*GetModelCommitResponse)(nil),      // 16: matrixhub.v1alpha1.GetModelCommitResponse
	(*GetModelTreeCommitsRequest)(nil),  // 17: matrixhub.v1alpha1.GetModelTreeCommitsRequest
	(*GetModelTreeCommitsResponse)(nil), // 18: matrixhub.v1alpha1.GetModelTreeCommitsResponse
	(*GetModelTreeRequest)(nil),         // 19: matrixhub.v1alpha1.GetModelTreeRequest
	(*GetModelTreeResponse)(nil),        // 20: matrixhub.v1alpha1.GetModelTreeResponse
	(*GetModelBlobRequest)(nil),         // 21: matrixhub.v1alpha1.GetModelBlobRequest
	(*GetModelBlobResponse)(nil),        // 22: matrixhub.v1alpha1.GetModelBlobResponse
	(*Model)(nil),                       // 23: matrixhub.v1alpha1.Model
	(*CloneUrls)(nil),                   // 24: matrixhub.v1alpha1.CloneUrls
	(*Label)(nil),                       // 25: matrixhub.v1alpha1.Label
	(*Branch)(nil),                      // 26: matrixhub.v1alpha1.Branch
	(*Tag)(nil),                         // 27: matrixhub.v1alpha1.Tag
	(*Pagination)(nil),                  // 28: matrixhub.v1alpha1.Pagination
}
var file_v1alpha1_model_proto_depIdxs = []int32{
	23, // 0: matrixhub.v1alpha1.ListModelsResponse.item:type_name -> matrixhub.v1alpha1.Model
	28, // 1: matrixhub.v1alpha1.ListModelsResponse.pagination:type_name -> matrixhub.v1alpha1.Pagination
	23, // 2: matrixhub.v1alpha1.GetModelResponse.model:type_name -> matrixhub.v1alpha1.Model
	26, // 3: matrixhub.v1alpha1.ListModelBranchesResponse.items:type_name -> matrixhub.v1alpha1.Branch
	25, // 4: matrixhub.v1alpha1.ListModelTagsResponse.items:type_name -> matrixhub.v1alpha1.Label
	16, // 5: matrixhub.v1alpha1.GetModelTreeCommitsResponse.items:type_name -> matrixhub.v1alpha1.GetModelCommitResponse
	22, // 6: matrixhub.v1alpha1.GetModelTreeResponse.items:type_name -> matrixhub.v1alpha1.GetModelBlobResponse
	0,  // 7: matrixhub.v1alpha1.GetModelBlobResponse.type:type_name -> matrixhub.v1alpha1.FileType
	24, // 8: matrixhub.v1alpha1.Model.clone_urls:type_name -> matrixhub.v1alpha1.CloneUrls
	27, // 9: matrixhub.v1alpha1.Model.tags:type_name -> matrixhub.v1alpha1.Tag
	1,  // 10: matrixhub.v1alpha1.Models.ListModels:input_type -> matrixhub.v1alpha1.ListModelsRequest
	3,  // 11: matrixhub.v1alpha1.Models.GetModel:input_type -> matrixhub.v1alpha1.GetModelRequest
	5,  // 12: matrixhub.v1alpha1.Models.CreateModel:input_type -> matrixhub.v1alpha1.CreateModelRequest
	7,  // 13: matrixhub.v1alpha1.Models.DeleteModel:input_type -> matrixhub.v1alpha1.DeleteModelRequest
	9,  // 14: matrixhub.v1alpha1.Models.ListModelBranches:input_type -> matrixhub.v1alpha1.ListModelBranchesRequest
	11, // 15: matrixhub.v1alpha1.Models.ListModelTags:input_type -> matrixhub.v1alpha1.ListModelTagsRequest
	13, // 16: matrixhub.v1alpha1.Models.GetModelLastCommit:input_type -> matrixhub.v1alpha1.GetModelLastCommitRequest
	15, // 17: matrixhub.v1alpha1.Models.GetModelCommit:input_type -> matrixhub.v1alpha1.GetModelCommitRequest
	17, // 18: matrixhub.v1alpha1.Models.GetModelTreeCommits:input_type -> matrixhub.v1alpha1.GetModelTreeCommitsRequest
	19, // 19: matrixhub.v1alpha1.Models.GetModelTree:input_type -> matrixhub.v1alpha1.GetModelTreeRequest
	21, // 20: matrixhub.v1alpha1.Models.GetModelBlob:input_type -> matrixhub.v1alpha1.GetModelBlobRequest
	2,  // 21: matrixhub.v1alpha1.Models.ListModels:output_type -> matrixhub.v1alpha1.ListModelsResponse
	4,  // 22: matrixhub.v1alpha1.Models.GetModel:output_type -> matrixhub.v1alpha1.GetModelResponse
	6,  // 23: matrixhub.v1alpha1.Models.CreateModel:output_type -> matrixhub.v1alpha1.CreateModelResponse
	8,  // 24: matrixhub.v1alpha1.Models.DeleteModel:output_type -> matrixhub.v1alpha1.DeleteModelResponse
	10, // 25: matrixhub.v1alpha1.Models.ListModelBranches:output_type -> matrixhub.v1alpha1.ListModelBranchesResponse
	12, // 26: matrixhub.v1alpha1.Models.ListModelTags:output_type -> matrixhub.v1alpha1.ListModelTagsResponse
	14, // 27: matrixhub.v1alpha1.Models.GetModelLastCommit:output_type -> matrixhub.v1alpha1.GetModelLastCommitResponse
	16, // 28: matrixhub.v1alpha1.Models.GetModelCommit:output_type -> matrixhub.v1alpha1.GetModelCommitResponse
	18, // 29: matrixhub.v1alpha1.Models.GetModelTreeCommits:output_type -> matrixhub.v1alpha1.GetModelTreeCommitsResponse
	20, // 30: matrixhub.v1alpha1.Models.GetModelTree:output_type -> matrixhub.v1alpha1.GetModelTreeResponse
	22, // 31: matrixhub.v1alpha1.Models.GetModelBlob:output_type -> matrixhub.v1alpha1.GetModelBlobResponse
	21, // [21:32] is the sub-list for method output_type
	10, // [10:21] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_v1alpha1_model_proto_init() }
func file_v1alpha1_model_proto_init() {
	if File_v1alpha1_model_proto != nil {
		return
	}
	file_v1alpha1_utils_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1alpha1_model_proto_rawDesc), len(file_v1alpha1_model_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1alpha1_model_proto_goTypes,
		DependencyIndexes: file_v1alpha1_model_proto_depIdxs,
		EnumInfos:         file_v1alpha1_model_proto_enumTypes,
		MessageInfos:      file_v1alpha1_model_proto_msgTypes,
	}.Build()
	File_v1alpha1_model_proto = out.File
	file_v1alpha1_model_proto_goTypes = nil
	file_v1alpha1_model_proto_depIdxs = nil
}
