// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: v1alpha1/utils.proto

package v1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Pagination is for data paging.
type Pagination struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Total is the total number of referents.
	Total int32 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	// Page is current page.
	Page int32 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	// PageSize is the data number shown per page.
	PageSize int32 `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Pages is the number of pages.
	Pages         int32 `protobuf:"varint,4,opt,name=pages,proto3" json:"pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pagination) Reset() {
	*x = Pagination{}
	mi := &file_v1alpha1_utils_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pagination) ProtoMessage() {}

func (x *Pagination) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_utils_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pagination.ProtoReflect.Descriptor instead.
func (*Pagination) Descriptor() ([]byte, []int) {
	return file_v1alpha1_utils_proto_rawDescGZIP(), []int{0}
}

func (x *Pagination) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *Pagination) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *Pagination) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *Pagination) GetPages() int32 {
	if x != nil {
		return x.Pages
	}
	return 0
}

var File_v1alpha1_utils_proto protoreflect.FileDescriptor

const file_v1alpha1_utils_proto_rawDesc = "" +
	"\n" +
	"\x14v1alpha1/utils.proto\x12\x12matrixhub.v1alpha1\"i\n" +
	"\n" +
	"Pagination\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x14\n" +
	"\x05pages\x18\x04 \x01(\x05R\x05pagesB<Z:github.com/matrixhub-ai/matrixhub/api/go/v1alpha1;v1alpha1b\x06proto3"

var (
	file_v1alpha1_utils_proto_rawDescOnce sync.Once
	file_v1alpha1_utils_proto_rawDescData []byte
)

func file_v1alpha1_utils_proto_rawDescGZIP() []byte {
	file_v1alpha1_utils_proto_rawDescOnce.Do(func() {
		file_v1alpha1_utils_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1alpha1_utils_proto_rawDesc), len(file_v1alpha1_utils_proto_rawDesc)))
	})
	return file_v1alpha1_utils_proto_rawDescData
}

var file_v1alpha1_utils_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_v1alpha1_utils_proto_goTypes = []any{
	(*Pagination)(nil), // 0: matrixhub.v1alpha1.Pagination
}
var file_v1alpha1_utils_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1alpha1_utils_proto_init() }
func file_v1alpha1_utils_proto_init() {
	if File_v1alpha1_utils_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1alpha1_utils_proto_rawDesc), len(file_v1alpha1_utils_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1alpha1_utils_proto_goTypes,
		DependencyIndexes: file_v1alpha1_utils_proto_depIdxs,
		MessageInfos:      file_v1alpha1_utils_proto_msgTypes,
	}.Build()
	File_v1alpha1_utils_proto = out.File
	file_v1alpha1_utils_proto_goTypes = nil
	file_v1alpha1_utils_proto_depIdxs = nil
}
